_target_: src.models.cp4sl_module.CP4SLLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.graph_dae.GraphDAE
  in_dim: 300
  n_nodes: 8
  hidden_dim: 300
  n_layers: 5
  gen_mode: TCNGen
  gen_act: elu
  k: 2
  knn_metric: cosine
  i_: 2
  normalization: sym
  dropout_dae: 0.5
  dropout_adj: 0.0
  graph_layer: GraphTCNConv

ratio: 20
nr: 5
noise: normal
